<a href="https://colab.research.google.com/github/phuonghnhut/learn01/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays

In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [5]:
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [6]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [7]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [8]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [10]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
e = np.random.random((2,2))
print(e)

[[0.75266283 0.31986328]
 [0.48459312 0.47745679]]


# Array indexing

In [12]:
import numpy as np

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.shape)
print(a)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
#chọn 2 hàng đầu tiên, lấy từ cột 1 đến cột 3 trừ cột 3
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [16]:
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

2
77


In [18]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [20]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(a)
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


# Toán

In [21]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

In [22]:
print(x + y)
print(" ")
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
 
[[ 6.  8.]
 [10. 12.]]


In [23]:
print(x - y)
print(" ")
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
 
[[-4. -4.]
 [-4. -4.]]


In [24]:
print(x * y)
print(" ")
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
 
[[ 5. 12.]
 [21. 32.]]


In [25]:
print(x / y)
print("")
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [27]:
# Nhân hai ma trân dot

In [29]:
v = np.array([9, 10])
w = np.array([11, 12])

In [30]:
print(v.dot(w))
print(" ")
print(np.dot(v, w))

219
 
219


In [31]:
print(x.dot(v))
print(" ")
print(np.dot(x, v))

[29. 67.]
 
[29. 67.]


In [32]:
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


Nump cung cấp nhiều hàm hữu ích để thực hiện các phép toán trên mảng

In [34]:
x = np.array([[1,2], [3,4]])
print(x.shape)
print(x.ndim)

(2, 2)
2


In [36]:
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
#axis=0 tương đướng với cột axis=1 tương đương với hàng

10
[4 6]
[3 7]


In [40]:
x

array([[1, 2],
       [3, 4]])

In [41]:
x.T

array([[1, 3],
       [2, 4]])

# Broadcasting
Broadcasting là một cơ chế mạnh mẽ cho phép numpy làm việc với các mảng có hình dạng khác nhau khi thực hiện các phép toán số học. Thông thường, chúng ta có một mảng nhỏ hơn và một mảng lớn hơn, và chúng ta muốn sử dụng mảng nhỏ hơn nhiều lần để thực hiện một số thao tác trên mảng lớn hơn

In [44]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [45]:
#Vi du voi Broadcasting 

In [47]:
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
